name: pull_request_to_dev

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
defaults:
  run:
    shell: bash

jobs:
  code_quality_check:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/code-quality-check.yml
    secrets: inherit
