name: New library version
on:
  pull_request:
    branches:
      - main
    types:
      - closed

defaults:
  run:
    shell: bash

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  FORCE_COLOR: 3

jobs:
  releaser:
    timeout-minutes: 5
    name: Release new version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publish
        id: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: bash ./scripts/publish.sh

      - name: Commit version
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          default_author: github_actor
          message: 'New library version ${{ env.LAST_TAG }} (publish)'
          fetch: false
          pathspec_error_handling: ignore
          push: true
      - name: Generate Notification
        id: notification
        continue-on-error: true
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Release Notification: ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":tada: *New Release Available* :tada:"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit SHA:*\n${{ github.sha }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Release Details"
                      },
                      "url": "https://github.com/${{ github.repository }}/releases/tag/${{ env.LAST_TAG }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Rust crate"
                      },
                      "url": "https://crates.io/crates/legend-saga/${{ env.LAST_TAG }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
